import Head from 'next/head'
import styles from '../styles/Home.module.css';
import { gsap } from "gsap";
import {useEffect, useRef} from "react";
import AOS from 'aos';
import 'aos/dist/aos.css';

export default function Home() {

  useEffect(() => {
    window.onscroll = function(){
      AOS.init({
        offset: 300,
        delay: 0, 
        duration: 700,
        once: false,
      });
    }
  })
  return (
    <>
      <Head>
        <title>Meow Squad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={styles.background}>
        
      <svg
            className={styles.scroll}
            width="40"
            height="77"
            viewBox="0 0 40 77"
            >
              <g id="scrollCircle" transform="translate(-253 -787)">
                <g
                  id="Rectangle_12"
                  transform="translate(253 787)"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="4"
                >
                  <rect width="40" height="77" rx="20" stroke="none"></rect>
                  <rect
                    x="2"
                    y="2"
                    width="36"
                    height="73"
                    rx="18"
                    fill="none"
                  ></rect>
                </g>
                <circle
                  className={styles.circle}
                  id="Ellipse_1"
                  cx="11"
                  cy="11"
                  r="11"
                  transform="translate(262 798)"
                  fill="#fff"
                ></circle>
              </g>
            </svg>

        <div className={styles.roadmap}>
          
          <div className={styles.first}>
            <div className={styles.fL} data-aos="fade-down">
              <img src="/paw.png" className={styles.firstPaw + " " + styles.paw}/>
              <div className={styles.firstLine}></div>
            </div>
            <div className={styles.firstTexts} data-aos="fade-left" data-aos-delay="100">
              <p className={styles.roadmapHeader}>June - September 2022</p>
              <div className={styles.roadmapText}>
                <div className={styles.ball + " " + styles.whiteBall}></div>
                <p>Release twitter-tracker</p>
              </div>
              <div className={styles.roadmapText}>
                <div className={styles.ball + " " + styles.whiteBall}></div>
                <p>Release twitter manager</p>
              </div>
              <div className={styles.roadmapText}>
                <div className={styles.ball + " " + styles.whiteBall}></div>
                <p>First batch of merch for pets</p>
              </div>
              <div className={styles.roadmapText}>
                <div className={styles.ball + " " + styles.whiteBall}></div>
                <p>First batch of merch for people</p>
              </div>
              <div className={styles.roadmapText}>
                <div className={styles.ball + " " + styles.whiteBall}></div>
                <p>Launching</p>
              </div>
              <div className={styles.roadmapText}>
                <div className={styles.ball + " " + styles.whiteBall}></div>
                <p>Release Staking</p>
              </div>
            </div>
          </div>

          <div className={styles.second}>
            <div className={styles.leftColumn} data-aos="fade-right" data-aos-delay="350" data-aos-offset="300">
              <div className={styles.secondLineLeft}>
                <img src="/paw.png" className={styles.paw}/>
                <div className={styles.sLL}></div>
              </div>

              <div className={styles.secondTexts}>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Release R2E tool as a service<br/> paid by $MEOW</p>
                </div>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Release service subscription<br/> format for holders paid by $MEOW</p>
                </div>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Start mailing merch for holders<br/>(for both people and cats)</p>
                </div>
              </div>
            </div>
            <div className={styles.middleColumn} data-aos="fade-down" data-aos-offset="300">
              <p className={styles.roadmapHeader}>Q4 2022</p>
              <div className={styles.middleLine}></div>
            </div>
            <div className={styles.rightColumn} data-aos="fade-left" data-aos-delay="750" data-aos-offset="300">
              <div className={styles.secondLineRight}>
                <div className={styles.sLR}></div>
                <img src="/paw.png" className={styles.paw}/>
              </div>
              <div className={styles.secondTexts}>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Auto-update tool for market data</p>
                </div>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Alerts tool</p>
                </div>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Mint manager</p>
                </div>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Mint Portfolio manager</p>
                </div>
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Platform for nft raffles</p>
                </div>
              </div>
            </div>
          </div>

          <div className={styles.third}>
            <p className={styles.roadmapHeader} data-aos="fade-down" data-aos-offset="150">Q1 2023</p>
            <div className={styles.thirdR}>
              <div data-aos="fade-up" data-aos-offset="150" data-aos-delay="500">
                <img src="/paw.png" className={styles.paw}/>
                <div className={styles.thirdLine}></div>
              </div>
              <div>
                <div className={styles.roadmapText} data-aos="fade-left" data-aos-offset="150" data-aos-delay="800">
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>Release big data based tool for analyzing twitter <br/>sentiment for each collection</p>
                </div>
              </div>
            </div>
          </div>

          <div className={styles.four}>
            <p className={styles.roadmapHeader} data-aos="fade-down" data-aos-offset="200">Q2-Q3 2023</p>
            <div className={styles.fourR}>
              <div className={styles.fourText}  data-aos="fade-right" data-aos-offset="200" data-aos-delay="400">
                <div className={styles.roadmapText}>
                  <div className={styles.ball + " " + styles.whiteBall}></div>
                  <p>IRL Events</p>
                </div>
              </div>
              <div>
                <img src="/paw.png" className={styles.paw}  data-aos="fade-down" data-aos-offset="150" data-aos-delay="100"/>
                <div className={styles.fourLine} data-aos="fade-down" data-aos-offset="150" data-aos-delay="100"></div>
                <p className={styles.tobe} data-aos="fade-up" data-aos-offset="100" data-aos-delay="1000">to be continued</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      
    </>
  )
}
